### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by vanjoechua** [AntonioPrimera/laravel-generator-command#1]
modification to isAbsolutePath method in FileGeneratorCommand class

```
protected function isAbsolutePath($path): bool
{
return in_array($path[0], ['/', '\\']) || strpos($path, ':\\');
}
```

**Comment by AntonioPrimera** [comment]
The entire package was rewritten and optimized. The antonioprimera/filesystem package was used, to handle all folder, file and path related tasks.

Please check if you still have this issue, because in the latest package version, there is no check for absolute paths anymore.

**Comment by vanjoechua** [comment]
I installed v2.3 on a new project and I get this error:

 Stub file C:\laragon\www\ptm-laravel\C:\laragon\www\ptm-laravel\vendor\antonioprimera\laravel-generator-command\src/stubs/GeneratorCommandStub.php.stub could not be found

at vendor\antonioprimera\laravel-generator-command\src\Stub.php:22

I am developing using Windows 10.

**Comment by vanjoechua** [comment]
I had to change this function in FileRecipe.php

```
protected function absolutePath(string|File|Folder $file): string
	{
//        return str_starts_with((string) $file, '/')
//            ? (string) $file
//            : base_path((string) $file);

        if(str_starts_with((string) $file, '/')) {
            return (string) $file;
        } else if(str_starts_with((string) $file, '\\')) {
            return (string) $file;
        } else if(strpos((string) $file, ':\\')) {
            return (string) $file;
        } else {
            return  base_path((string) $file);
        }
}
```
